# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: calculo-servicio.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16\x63\x61lculo-servicio.proto\x12\x07\x63\x61lculo\")\n\x0bSumaRequest\x12\x0c\n\x04num1\x18\x01 \x01(\x02\x12\x0c\n\x04num2\x18\x02 \x01(\x02\"*\n\x0cRestaRequest\x12\x0c\n\x04num1\x18\x01 \x01(\x02\x12\x0c\n\x04num2\x18\x02 \x01(\x02\"%\n\x10OperacionRequest\x12\x11\n\toperacion\x18\x01 \x01(\t\"&\n\x11OperacionResponse\x12\x11\n\tresultado\x18\x01 \x01(\x02\x32\xcd\x01\n\x0b\x43\x61lculadora\x12:\n\x04Suma\x12\x14.calculo.SumaRequest\x1a\x1a.calculo.OperacionResponse\"\x00\x12<\n\x05Resta\x12\x15.calculo.RestaRequest\x1a\x1a.calculo.OperacionResponse\"\x00\x12\x44\n\tOperacion\x12\x19.calculo.OperacionRequest\x1a\x1a.calculo.OperacionResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'calculo_servicio_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_SUMAREQUEST']._serialized_start=35
  _globals['_SUMAREQUEST']._serialized_end=76
  _globals['_RESTAREQUEST']._serialized_start=78
  _globals['_RESTAREQUEST']._serialized_end=120
  _globals['_OPERACIONREQUEST']._serialized_start=122
  _globals['_OPERACIONREQUEST']._serialized_end=159
  _globals['_OPERACIONRESPONSE']._serialized_start=161
  _globals['_OPERACIONRESPONSE']._serialized_end=199
  _globals['_CALCULADORA']._serialized_start=202
  _globals['_CALCULADORA']._serialized_end=407
# @@protoc_insertion_point(module_scope)
